In [11]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'1.12.1'

In [12]:
from torch.multiprocessing import Pool, Process, set_start_method
try:
     set_start_method('spawn')
except RuntimeError:
    pass

In [13]:
!nvidia-smi

Sat Feb 25 16:31:50 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 511.23       Driver Version: 511.23       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   47C    P8     8W /  N/A |    229MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [14]:
# cuda 사용가능한지 boolean 반환
torch.cuda.is_available()

False

In [15]:
device = 'cuda' if torch.cuda.is_available() else "cpu"
device # 상황에 따라 자주 사용하는 변수 선언

'cpu'

In [16]:
# device 개수 반환
torch.cuda.device_count()

0

In [17]:
tensor = torch.tensor([1,2,3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

# tensor.to(device)
- cuda 가 가능할 때 device 설정 변경
- **device 가 cuda 일 때, numpy() 메소드 사용 불가**

In [18]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3]), device(type='cpu'))

In [19]:
# device: cuda > cpu > numpy
# tensor.cuda()
tensor_on_gpu.cpu().numpy()

array([1, 2, 3], dtype=int64)