In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'1.12.1'

# 랜덤 숫자 생성

In [25]:
random_tensor = torch.rand(4, 4)
random_tensor

tensor([[0.9605, 0.4358, 0.7207, 0.8350],
        [0.7066, 0.9667, 0.9903, 0.4845],
        [0.5511, 0.7695, 0.4293, 0.2444],
        [0.3912, 0.3216, 0.6361, 0.2330]])

In [26]:
random_tensor.ndim

2

In [31]:
# 랜덤 이미지 컬러 값 생성
random_image_size_tensor = torch.rand(size=(3, 244, 244)) # col, height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 244, 244]), 3)

# Zeros / Ones

In [53]:
zeros = torch.zeros(size=(3, 4))
print(zeros, zeros.dtype, '\n')

ones = torch.ones(size=(3, 4))
print(ones, ones.dtype)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) torch.float32 

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) torch.float32


# torch.zero_like(input=torch data)
# torch.one_like(input=torch data)

In [ ]:
# 미래에 사라질 방식 || torch.range()
# zero_to_ten_deprecated = torch.range(0, 10)

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
# zero_to_ten 과 같은 shape 의 영행렬 일행렬 생성
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_ones = torch.ones_like(input=zero_to_ten) 

ten_zeros, ten_ones

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))