In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'1.12.1'

# 단순 이항 연산자 사용

In [62]:
tensor = torch.tensor([1, 2, 3])
tensor + 10, tensor - 10, tensor * 10, tensor / 4

(tensor([11, 12, 13]),
 tensor([-9, -8, -7]),
 tensor([10, 20, 30]),
 tensor([0.2500, 0.5000, 0.7500]))

# tensor 끼리의 연산

In [63]:
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


# 연산 메소드 사용 || add, subtract, multiply, divide
- 이항 연산자보단 메소드 사용을 지향하자. (속도 때문)

In [78]:
torch.add(tensor, 10), torch.subtract(tensor, 10), torch.multiply(tensor, 10), torch.divide(tensor, 10)

(tensor([11, 12, 13]),
 tensor([-9, -8, -7]),
 tensor([10, 20, 30]),
 tensor([0.1000, 0.2000, 0.3000]))