In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'1.12.1'

In [2]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [12]:
print(f"First square bracket:\n{x[0]}\n") 
print(f"Second square bracket: {x[0][0]}\n") 
print(f"Third square bracket: {x[0][0][0]}\n")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Second square bracket: tensor([1, 2, 3])

Third square bracket: 1



In [15]:
# x[:, 0] - 전체 높이 중에 첫 번째 행
# x[:, :, 1] - 전체 높이, 행 중에 두 번째 열
# x[:, 1, 1] - 전체 높이 중에 두 번째 행, 두 번째 열

x[:, 0], x[:, :, 1], x[:, 1, 1]

(tensor([[1, 2, 3]]), tensor([[2, 5, 8]]), tensor([5]))

In [16]:
# 첫 번째 높이, 첫 번째 행의 전체 열
x[0, 0, :] 

tensor([1, 2, 3])