In [3]:
import numpy as np

# 배열 타입 설정

In [4]:
list_1 = [50,30,5,56,6,65,7,4,3,63,36,4,5,6,34,55]

In [44]:
my_numpy_array = np.array(list_1) # 여러 차원 배열도 가능
print(my_numpy_array)
print(my_numpy_array.dtype)

my_numpy_array = np.array(list_1, dtype='f4') # 타입 설정 가능
print(my_numpy_array)
print(my_numpy_array.dtype)

my_numpy_array = np.array(['abc', 'defasgbg'], dtype='S3') # 문자열 길이 제한 가능
print(my_numpy_array)
print(my_numpy_array.dtype)

# 배열 안의 가장 긴 문자열을 크기를 타입으로 사용됨
my_numpy_array = np.array(['a', 'ab', 'abc'], dtype=np.string_) 
print(my_numpy_array)
print(my_numpy_array.dtype)

# 배열 안의 가장 긴 문자열을 크기를 타입으로 사용됨
my_numpy_array = np.array(['a', 'ab', 'abc'], dtype=np.unicode_) 
print(my_numpy_array)
print(my_numpy_array.dtype)

[50 30  5 56  6 65  7  4  3 63 36  4  5  6 34 55]
int32
[50. 30.  5. 56.  6. 65.  7.  4.  3. 63. 36.  4.  5.  6. 34. 55.]
float32
[b'abc' b'def']
|S3
[b'a' b'ab' b'abc']
|S3
['a' 'ab' 'abc']
<U3


# 배열 생성

In [74]:
list_2 = [0,1,2,3,4,5,6,7,8,9,]
arr1 = np.array(list_2) # 1차원 배열
arr2 = np.array(range(10)) # 시퀸스 객체
arr3 = np.array([[1,2,3], [4,5,6]]) # 2차원 배열 직접 삽입
arr4 = np.arange(0, 20) # array와 range 합친 메소드
arr5 = np.arange(0, 20, 2) 
arr6 = np.linspace(0, 10, 20) # 등분 간격 유지하는 수 배열
arr7, step = np.linspace(0, 10, 20, endpoint=False, retstep=True) # 간격을 반환을 같이 받기 



# 특수한 배열 생성

In [ ]:
a = np.eye(7) # 주대각선이 1이고 나머지가 0인 7x7의 대각행렬 반환
b = np.eye(5, k=-2) # 대각행렬의 대각 위치 조정
c = np.identity(3) # 단위행렬
d = np.ones((7,7)) # 7x7의 1행렬 반환
e = np.ones_like(arr1) # 특정 배열의 형태대로 1행렬 반환
f = np.zeros(8) # 8x8의 영행렬 반환
g = np.zeros_like(arr1) # 특정 배열의 형태대로 영행렬 반환
h = np.full((2,3), 5) # 2x3의 5행렬 반환
i = np.full_like(arr1, 5) # 특정 배열의 형태대로 5행렬 반환
j = np.diag(arr1) # 1차원 배열 인자 -> 대각행렬로 반환
k = np.diag(arr3) # 2차원 배열 인자 -> 주대각선 성분 추출 반환



# 난수 생성과 활용

In [97]:
arr = np.arange(25).reshape(5,5)

np.random.seed(123) # 랜덤 시드 숫자 고정
l = np.random.rand(20) # 랜덤 실수 - 20개의 배열 반환
m = np.random.rand(3, 3) # 랜덤 실수 - 행렬 3x3 의 배열 반환
# np.ranodm.randint(low, high, size, dtype)
n = np.random.randint(1, 50) # 랜덤 정수 - 1~50 사이의 수 1개 정수 반환
o = np.random.randint(1, 100, 15) # 랜덤 정수 - 1~100 사이의 수 15개 배열 반환



In [98]:
# np.random.rand()
print(np.random.random_sample(10))
print(np.random.random(10))
print(np.random.ranf(10))
print(np.random.sample(10))

[0.46426806 0.56843069 0.30254945 0.49730879 0.68326291 0.91669867
 0.10892895 0.49549179 0.23283593 0.43686066]
[0.75154299 0.48089213 0.79772841 0.28270293 0.43341824 0.00975735
 0.34079598 0.68927201 0.86936929 0.26780382]
[0.45674792 0.26828131 0.8370528  0.27051466 0.53006201 0.17537266
 0.31496645 0.8911091  0.18033628 0.4943162 ]
[0.2122981  0.52087687 0.16009994 0.9190568  0.99428992 0.47704756
 0.30988351 0.50720432 0.2807932  0.76383669]


In [85]:
# np.random.choice(iterable_or_int, size, replace=True, p=weights)
print(np.random.choice(range(4), 15, replace=True, p=[0.3, 0.2, 0.1, 0.4]))
print(np.random.choice(6, 15))

[3 3 2 0 3 3 1 0 0 3 0 0 0 3 3]
[3 0 3 1 0 4 0 2 2 4 2 5 2 5 2]


In [103]:
# 배열의 요소 순서 섞기
print(f'shuffle 하기 전 \n{arr}')
print()
print(np.random.shuffle(arr)) # None
print()
print(f'shuffle 한 후 \n{arr}')
print()
# 배열의 요소 순서 섞은 것을 복사
print(np.random.permutation(arr))


shuffle 하기 전 
[[10 11 12 13 14]
 [20 21 22 23 24]
 [ 0  1  2  3  4]
 [15 16 17 18 19]
 [ 5  6  7  8  9]]

None

shuffle 한 후 
[[15 16 17 18 19]
 [20 21 22 23 24]
 [ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[10 11 12 13 14]
 [15 16 17 18 19]
 [ 5  6  7  8  9]
 [20 21 22 23 24]
 [ 0  1  2  3  4]]


# 반복을 사용한 배열 생성

In [77]:
arr = [0, 1, 2]
print(np.repeat(arr, 3))  
print()
print(np.repeat(range(3), 3))
print()

# 배열의 반복 위치 설정, 축 설정
arr = [[1,2], [3,4]]
print(np.repeat(arr, [1,5], axis=0))

[0 0 0 1 1 1 2 2 2]

[0 0 0 1 1 1 2 2 2]


# 배열 연산

In [104]:
a = np.arange(1, 10) # [1~9] nparray 형태가 됨
b = np.arange(1, 10) # [1~9] nparray 형태가 됨

sum_ = a + b # 각 인덱스별 더하기 결과를 반환
print(f'{a}\n{b}\n{sum_}')

minus = a - b # 각 인덱스별 더하기 결과를 반환
print(f'{a}\n{b}\n{minus}')

squared = a ** 2 # 배열 제곱 인덱스별 적용
print(a, squared)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14 16 18]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[0 0 0 0 0 0 0 0 0]
[1 2 3 4 5 6 7 8 9] [ 1  4  9 16 25 36 49 64 81]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]


In [121]:
arr1 = np.array([1,2,3])
arr2 = np.array([8,9,10])

np.add(arr1, arr2, out=arr1)
print(arr1) # arr1 변수에 더하기 결과 반환
print(arr2) # arr2 의 값이 변하지 않음

np.subtract(arr1, [8,9,10]) # out 파라미터에 변수를 주지 않으면 반환 안함
print(arr1)
print(arr2)

np.multiply(arr1, [1,2,3], out=arr1)
print(arr1)

[ 9 11 13]
[ 8  9 10]
[ 9 11 13]
[ 8  9 10]
[ 9 22 39]


In [130]:
arr = np.arange(1,7).reshape(2,3)
print(np.sqrt(arr)) # 배열 제곱근 인덱스별 적용
print(np.exp(arr)) # 자연상수(e = 2.71828...)의 지수배에 대한 값을 계산

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [131]:
print(arr)
print(np.log(arr)) # 자연 로그
print(np.log2(arr)) # log2
print(np.log10(arr))    

[[1 2 3]
 [4 5 6]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]
[[0.         1.         1.5849625 ]
 [2.         2.32192809 2.5849625 ]]
[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]]


In [ ]:
print(np.sin(arr))
print(np.cos(arr))

In [136]:
print(arr)
print()
print(np.sum(arr, axis=0))
print()
print(np.sum(arr, axis=1))  

[[1 2 3]
 [4 5 6]]

[5 7 9]
[ 6 15]


In [139]:
print(arr)
print()
# 축을 따라 최솟값 반환
print(np.min(arr, axis=0))
print(np.min(arr, axis=1))
print(np.min(arr)) # 축이 없으면 최솟값 반환

[[1 2 3]
 [4 5 6]]

[1 2 3]
[1 4]
1


In [142]:
print(arr)
print()
# 축을 따라 최댓값 반환
print(np.max(arr, axis=0))    
print(np.max(arr, axis=1))    
print(np.max(arr)) # 축이 없으면 최댓값 반환

[[1 2 3]
 [4 5 6]]

[4 5 6]
[3 6]
6


In [145]:
# 축을 따라 최댓값, 최소값의 인덱스 반환
print(np.argmin(arr, axis=0))
print(np.argmax(arr, axis=0))
print(np.argmin(arr, axis=1))
print(np.argmax(arr, axis=1))
# 축이 없으면 전체 요소 중 최댓값의 인덱스, 최솟값의 인덱스 반환
print(np.argmin(arr))
print(np.argmax(arr))

[0 0 0]
[1 1 1]
[0 0]
[2 2]
0
5


In [146]:
arr1 = np.array([1, 2, 4, 7, 5])
arr2 = np.array([0, 4, 3, 5, 9])

# 길이와 차원이 같은 배열의 같은 인덱스 끼리 비교후 큰 값 배열, 작은 값 배열 반환
print(np.maximum(arr1, arr2))
print(np.minimum(arr1, arr2))

[1 4 4 7 9]
[0 2 3 5 5]


In [147]:
arr1 = np.random.rand(10) * 10

# 배열의 정수 부분과 소수 부분을 분리
float_, int_ = np.modf(arr1)
print(arr1)
print(int_)
print(float_)

[5.52043722 2.40247504 8.84805011 4.60238424 1.9317033  2.93692504
 8.17927508 5.59487376 6.77925447 8.09126678]
[5. 2. 8. 4. 1. 2. 8. 5. 6. 8.]
[0.52043722 0.40247504 0.84805011 0.60238424 0.9317033  0.93692504
 0.17927508 0.59487376 0.77925447 0.09126678]


# 인덱싱, 슬라이싱

In [56]:
# Broadcasting 방법
# 한 번에 특정 슬라이싱 범위를 값을 바꾸기
my_numpy_array[0:6] = 99
print(my_numpy_array)
print()

matrix = np.random.randint(1,10, (4,4))
print(matrix)
print()

# get first row 
# get first row's second index
print(f'{matrix[0]} {matrix[0][1]}')
print()

# [행, 열] 표기법 가능
print(matrix[1, 3])
print()

# boolean indexing
matrix = np.random.randint(1, 10, (5, 5))
new_matrix = matrix[ matrix > 7]
print(new_matrix)
print()

# boolean indexing
new_matrix = matrix[ matrix % 2 == 0 ] # 짝수 값만 배열 반환
print(new_matrix)
print()

# fancy indexing
print(matrix[[0, 2]])
print()


['99' '99' '99']

[[3 9 1 1]
 [1 1 5 7]
 [8 7 1 5]
 [7 7 7 8]]

[3 9 1 1] 9

7

[8 8 8 9]

[8 4 6 8 6 4 6 2 4 8 6 4 2]

[[1 8 3 4 6]
 [2 4 3 8 6]]



In [40]:
# 조건 2 개 값 일괄 변경
X = [[2, 30, 20, -2, -4],
    [3, 4, 40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]]

X = np.array(X)

X[ X < 0 ] = 0
X[ X % 2 == 1 ] = -2

X

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

# 배열 정보 확인

In [83]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]], dtype='i2')

print(x)
print(f'배열 타입 확인 {type(x)}')
print(f'배열 차원 확인 {x.ndim}')
print(f'배열 원소 개수 확인 {x.size}')
print(f'배열 모양 확인 {x.shape}')
print(f'각 배열 요소의 바이트 수 {x.itemsize}')
print(f'배열의 메모리 크기 {x.nbytes}')
print()
print(f'배열 종합 정보 확인 \n{np.info(x)}')


[[1 2 3]
 [4 5 6]
 [7 8 9]]
배열 타입 확인 <class 'numpy.ndarray'>
배열 차원 확인 2
배열 원소 개수 확인 9
배열 모양 확인 (3, 3)

class:  ndarray
shape:  (3, 3)
strides:  (6, 2)
itemsize:  2
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x170532249e0
byteorder:  little
byteswap:  False
type: int16
배열 종합 정보 확인 
None

각 배열 요소의 바이트 수 2
배열의 메모리 크기 18


# 배열 가공, 수정

In [72]:
print(x.reshape(1,9))
print()

print(x.reshape(9,1))
print()

print(x.astype(np.float32))

[[1 2 3 4 5 6 7 8 9]]

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# 확률과 통계