In [2]:
import numpy as np

# 배열 타입 설정

In [153]:
list_1 = [50,30,5,56,6,65,7,4,3,63,36,4,5,6,34,55]

In [155]:
my_numpy_array = np.array(list_1) # 여러 차원 배열도 가능
print(my_numpy_array)
print(my_numpy_array.dtype)

my_numpy_array = np.array(list_1, dtype='f4') # 타입 설정 가능
print(my_numpy_array)
print(my_numpy_array.dtype)

my_numpy_array = np.array(['abc', 'defasgbg'], dtype='S3') # 문자열 길이 제한 가능
print(my_numpy_array)
print(my_numpy_array.dtype)

# 배열 안의 가장 긴 문자열을 크기를 타입으로 사용됨
my_numpy_array = np.array(['a', 'ab', 'abc'], dtype=np.string_) 
print(my_numpy_array)
print(my_numpy_array.dtype)

# 배열 안의 가장 긴 문자열을 크기를 타입으로 사용됨
my_numpy_array = np.array(['a', 'ab', 'abc'], dtype=np.unicode_) 
print(my_numpy_array)
print(my_numpy_array.dtype)

[50 30  5 56  6 65  7  4  3 63 36  4  5  6 34 55]
int32
[50. 30.  5. 56.  6. 65.  7.  4.  3. 63. 36.  4.  5.  6. 34. 55.]
float32
[b'abc' b'def']
|S3
[b'a' b'ab' b'abc']
|S3
['a' 'ab' 'abc']
<U3


# 배열 생성

In [156]:
list_2 = [0,1,2,3,4,5,6,7,8,9,]
arr1 = np.array(list_2) # 1차원 배열
arr2 = np.array(range(10)) # 시퀸스 객체
arr3 = np.array([[1,2,3], [4,5,6]]) # 2차원 배열 직접 삽입
arr4 = np.arange(0, 20) # array와 range 합친 메소드
arr5 = np.arange(0, 20, 2) 
arr6 = np.linspace(0, 10, 20) # 등분 간격 유지하는 수 배열
arr7, step = np.linspace(0, 10, 20, endpoint=False, retstep=True) # 간격을 반환을 같이 받기 



# 특수한 배열 생성

In [164]:
a = np.eye(7) # 주대각선이 1이고 나머지가 0인 7x7의 대각행렬 반환
b = np.eye(5, k=-2) # 대각행렬의 대각 위치 조정
c = np.identity(3) # 단위행렬
d = np.ones((7,7)) # 7x7의 1행렬 반환
e = np.ones_like(arr1) # 특정 배열의 형태대로 1행렬 반환
f = np.zeros(8) # 8x8의 영행렬 반환
g = np.zeros_like(arr1) # 특정 배열의 형태대로 영행렬 반환
h = np.full((2,3), 5) # 2x3의 5행렬 반환
i = np.full_like(arr1, 5) # 특정 배열의 형태대로 5행렬 반환
j = np.diag(arr1) # 1차원 배열 인자 -> 대각행렬로 반환
k = np.diag(arr3) # 2차원 배열 인자 -> 주대각선 성분 추출 반환

j

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

# 난수 생성과 활용

In [168]:
arr = np.arange(25).reshape(5,5)

np.random.seed(123) # 랜덤 시드 숫자 고정
l = np.random.rand(20) # 랜덤 실수 - 20개의 배열 반환
m = np.random.rand(3, 3) # 랜덤 실수 - 행렬 3x3 의 배열 반환
# np.ranodm.randint(low, high, size, dtype)
n = np.random.randint(1, 50) # 랜덤 정수 - 1~50 사이의 수 1개 정수 반환
o = np.random.randint(1, 100, 15) # 랜덤 정수 - 1~100 사이의 수 15개 배열 반환



array([ 4, 70, 65, 76, 35, 59, 11, 23, 78, 19, 16, 28, 31, 53, 71])

In [169]:
# np.random.rand()
print(np.random.random_sample(10))
print(np.random.random(10))
print(np.random.ranf(10))
print(np.random.sample(10))



[0.46426806 0.56843069 0.30254945 0.49730879 0.68326291 0.91669867
 0.10892895 0.49549179 0.23283593 0.43686066]
[0.75154299 0.48089213 0.79772841 0.28270293 0.43341824 0.00975735
 0.34079598 0.68927201 0.86936929 0.26780382]
[0.45674792 0.26828131 0.8370528  0.27051466 0.53006201 0.17537266
 0.31496645 0.8911091  0.18033628 0.4943162 ]
[0.2122981  0.52087687 0.16009994 0.9190568  0.99428992 0.47704756
 0.30988351 0.50720432 0.2807932  0.76383669]


In [172]:
# np.random.choice(iterable_or_int, size, replace=True, p=weights)
print(np.random.choice(range(4), 15, replace=True, p=[0.3, 0.2, 0.1, 0.4]))
print(np.random.choice(6, 15))

[0 0 3 2 3 3 3 1 0 1 2 2 1 3 3]
[5 1 3 2 3 1 1 3 3 2 4 0 3 2 3]


In [173]:
# 배열의 요소 순서 섞기
print(f'shuffle 하기 전 \n{arr}')
print()
print(np.random.shuffle(arr)) # None
print()
print(f'shuffle 한 후 \n{arr}')
print()
# 배열의 요소 순서 섞은 것을 복사
print(np.random.permutation(arr))


shuffle 하기 전 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

None

shuffle 한 후 
[[ 0  1  2  3  4]
 [15 16 17 18 19]
 [ 5  6  7  8  9]
 [20 21 22 23 24]
 [10 11 12 13 14]]

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [ 5  6  7  8  9]
 [15 16 17 18 19]]


# 반복을 사용한 배열 생성

In [175]:
arr = [0, 1, 2]
print(np.repeat(arr, 3))  
print()
print(np.repeat(range(3), 3))
print()

# 배열의 반복 위치 설정, 축 설정
arr = [[1,2], [3,4]]
print(np.repeat(arr, [1,5], axis=0))

[0 0 0 1 1 1 2 2 2]

[0 0 0 1 1 1 2 2 2]

[[1 2]
 [3 4]
 [3 4]
 [3 4]
 [3 4]
 [3 4]]


# 배열 연산

In [176]:
a = np.arange(1, 10) # [1~9] nparray 형태가 됨
b = np.arange(1, 10) # [1~9] nparray 형태가 됨

sum_ = a + b # 각 인덱스별 더하기 결과를 반환
print(f'{a}\n{b}\n{sum_}')

minus = a - b # 각 인덱스별 더하기 결과를 반환
print(f'{a}\n{b}\n{minus}')

squared = a ** 2 # 배열 제곱 인덱스별 적용
print(a, squared)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14 16 18]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[0 0 0 0 0 0 0 0 0]
[1 2 3 4 5 6 7 8 9] [ 1  4  9 16 25 36 49 64 81]


In [177]:
arr1 = np.array([1,2,3])
arr2 = np.array([8,9,10])

np.add(arr1, arr2, out=arr1)
print(arr1) # arr1 변수에 더하기 결과 반환
print(arr2) # arr2 의 값이 변하지 않음

np.subtract(arr1, [8,9,10]) # out 파라미터에 변수를 주지 않으면 반환 안함
print(arr1)
print(arr2)

np.multiply(arr1, [1,2,3], out=arr1)
print(arr1)

[ 9 11 13]
[ 8  9 10]
[ 9 11 13]
[ 8  9 10]
[ 9 22 39]


In [130]:
arr = np.arange(1,7).reshape(2,3)
print(np.sqrt(arr)) # 배열 제곱근 인덱스별 적용
print(np.exp(arr)) # 자연상수(e = 2.71828...)의 지수배에 대한 값을 계산

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [131]:
print(arr)
print(np.log(arr)) # 자연 로그
print(np.log2(arr)) # log2
print(np.log10(arr))    

[[1 2 3]
 [4 5 6]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]
[[0.         1.         1.5849625 ]
 [2.         2.32192809 2.5849625 ]]
[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]]


In [ ]:
print(np.sin(arr))
print(np.cos(arr))

In [178]:
print(arr)
print()
print(np.sum(arr, axis=0))
print()
print(np.sum(arr, axis=1))  

[[1, 2], [3, 4]]

[4 6]

[3 7]


In [179]:
print(arr)
print()
# 축을 따라 최솟값 반환
print(np.min(arr, axis=0))
print(np.min(arr, axis=1))
print(np.min(arr)) # 축이 없으면 최솟값 반환

[[1, 2], [3, 4]]

[1 2]
[1 3]
1


In [142]:
print(arr)
print()
# 축을 따라 최댓값 반환
print(np.max(arr, axis=0))    
print(np.max(arr, axis=1))    
print(np.max(arr)) # 축이 없으면 최댓값 반환

[[1 2 3]
 [4 5 6]]

[4 5 6]
[3 6]
6


In [145]:
# 축을 따라 최댓값, 최소값의 인덱스 반환
print(np.argmin(arr, axis=0))
print(np.argmax(arr, axis=0))
print(np.argmin(arr, axis=1))
print(np.argmax(arr, axis=1))
# 축이 없으면 전체 요소 중 최댓값의 인덱스, 최솟값의 인덱스 반환
print(np.argmin(arr))
print(np.argmax(arr))

[0 0 0]
[1 1 1]
[0 0]
[2 2]
0
5


In [180]:
arr1 = np.array([1, 2, 4, 7, 5])
arr2 = np.array([0, 4, 3, 5, 9])

# 길이와 차원이 같은 배열의 같은 인덱스 끼리 비교후 큰 값 배열, 작은 값 배열 반환
print(np.maximum(arr1, arr2))
print(np.minimum(arr1, arr2))

[1 4 4 7 9]
[0 2 3 5 5]


In [44]:
arr1 = np.random.rand(10) * 10

# 배열의 정수 부분과 소수 부분을 분리
float_, int_ = np.modf(arr1)
print(arr1)
print(int_)
print(float_)

[7.10075224 2.94516994 9.71363999 2.7868747  0.69982189 5.19280361
 6.94314886 2.44659787 3.38582202 5.63627983]
[7. 2. 9. 2. 0. 5. 6. 2. 3. 5.]
[0.10075224 0.94516994 0.71363999 0.7868747  0.69982189 0.19280361
 0.94314886 0.44659787 0.38582202 0.63627983]


# 인덱싱, 슬라이싱

In [60]:
# Broadcasting 방법
# 한 번에 특정 슬라이싱 범위를 값을 바꾸기
my_numpy_array[0:6] = 99
print(my_numpy_array)
print()

matrix = np.random.randint(1,10, (4,4))
print(matrix)
print()

# get first row 
# get first row's second index
print(f'{matrix[0]} {matrix[0][1]}')
print()

# [행, 열] 표기법, 
print(matrix[1][3])
print(matrix[1, 3])
print()

# [...] 표기법 가능
print(matrix[1:3, 2:5])
print(matrix[1, ...])   
print(matrix[1,:])   
print()

['99' '99' '99']

[[8 4 6 5]
 [1 9 1 3]
 [2 6 6 6]
 [4 6 5 3]]

[8 4 6 5] 4

3
3

[[1 3]
 [6 6]]
[1 9 1 3]
[1 9 1 3]



In [69]:
print(matrix)
print()

# boolean indexing
bools = np.array([True, True, False, True, False])
print(matrix[1,:][bools])
print(matrix[1,:][~bools]) # not 붙인 효과
print()

# boolean indexing
matrix = np.random.randint(1, 10, (5, 5))
new_matrix = matrix[ matrix > 7]
print(new_matrix)
print()

# boolean indexing
new_matrix = matrix[ matrix % 2 == 0 ] # 짝수 값만 배열 반환
print(new_matrix)
print()

[[3 6 2 9 6]
 [9 2 4 1 5]
 [5 9 3 5 3]
 [2 8 3 4 1]
 [5 6 8 1 3]]

[9 2 1]
[4 5]

[9 8 8 8 9 8 8]

[8 6 8 8 2 6 2 6 6 2 8 8]



In [70]:
print(matrix)
print()

# fancy indexing
print(matrix[[0, 2]])
print()


[[7 9 8 6 7]
 [8 8 3 2 7]
 [1 6 3 7 2]
 [6 3 6 7 5]
 [2 9 8 8 1]]

[[7 9 8 6 7]
 [1 6 3 7 2]]



In [71]:
# 조건 2 개 값 일괄 변경
X = [[2, 30, 20, -2, -4],
    [3, 4, 40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]]

X = np.array(X)

X[ X < 0 ] = 0
X[ X % 2 == 1 ] = -2

X

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

# 조건에 따른 값 지정

In [83]:
# condition 
# np.where(condition, true_return, false_return) 
print(np.where(matrix > 5, 1, 0)) # true일 때, false일 때 삽입할 값 지정 가능
print()

# 조건에 맞는 값의 인덱스를 오름차순 반환
print(np.argwhere(matrix > 5))

[[1 1 1 1 1]
 [1 1 0 0 1]
 [0 1 0 1 0]
 [1 0 1 1 0]
 [0 1 1 1 0]]

[[0 0]
 [0 1]
 [0 2]
 [0 3]
 [0 4]
 [1 0]
 [1 1]
 [1 4]
 [2 1]
 [2 3]
 [3 0]
 [3 2]
 [3 3]
 [4 1]
 [4 2]
 [4 3]]


# 배열 정보 확인

In [106]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]], dtype='i2')

print(x)
print(f'배열 타입 확인 {type(x)}')
print(f'배열 차원 확인 {x.ndim}')
print(f'배열 원소 개수 확인 {x.size}')
print(f'배열 모양 확인 {x.shape}')
print(f'각 배열 요소의 바이트 수 {x.itemsize}')
print(f'배열의 메모리 크기 {x.nbytes}')
print()
print(f'배열 종합 정보 확인 \n{np.info(x)}')


[[1 2 3]
 [4 5 6]
 [7 8 9]]
배열 타입 확인 <class 'numpy.ndarray'>
배열 차원 확인 2
배열 원소 개수 확인 9
배열 모양 확인 (3, 3)
각 배열 요소의 바이트 수 2
배열의 메모리 크기 18

class:  ndarray
shape:  (3, 3)
strides:  (6, 2)
itemsize:  2
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x1ffee0a87f0
byteorder:  little
byteswap:  False
type: int16
배열 종합 정보 확인 
None


# 배열 가공, 수정

In [119]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]], dtype='i2')

print(x.reshape(1,9)) # 배열 shape 조정
print()

print(x.astype(np.float32)) # 배열의 요소들의 타입 지정
print()

x.resize((2,3)) # 배열의 사이즈 조정, slicing도 가능
print(x)
print()

print(x.flatten()) # 1차원 배열 반환 (메모리 저장)
print()

print(x.ravel()) # 1차원 배열 반환 (메모리 참조)


[[1 2 3 4 5 6 7 8 9]]

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]
[1 2 3 4 5 6]


# 배열 추가, 수정, 삭제, 복사

In [126]:
arr = np.array(range(1,4))
print(arr)
print()

# np.append(array, new_value, [axis])
arr1 = np.append(arr, 4)  
arr2 = np.append(arr, [4,5,6])    
print(arr1)
print(arr2)
print()

# np.insert(array, index, new_value. [axis])
arr3 = np.insert(arr, 0, 100)    
arr4 = np.insert(arr, 0, [1,2,3])    
print(arr3)
print(arr4)
print()

# np.delet(array, index)
arr5 = np.delete(arr, 0)    
print(arr5)
print()

# np.copy(array)
arr1 = np.copy(arr)

[1 2 3]

[1 2 3 4]
[1 2 3 4 5 6]

[100   1   2   3]
[1 2 3 1 2 3]

[2 3]



In [141]:
x = np.arange(1,17).reshape(4,4)
y = x.copy()

# np.concatename()
cat = np.concatenate((x,y))     
print(cat)   
cat = np.concatenate((x,y), axis=1)     
print(cat)   

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4  1  2  3  4]
 [ 5  6  7  8  5  6  7  8]
 [ 9 10 11 12  9 10 11 12]
 [13 14 15 16 13 14 15 16]]


# 배열 정렬

In [89]:
x = np.random.randint(1, 20, 16).reshape(4,4)
print(x)
print(np.sort(x, axis=0)) 
print(x.sort(axis=0))
print(x)


[[ 5 10 10 11]
 [ 8  5 10 11]
 [10 18  3  2]
 [13 14  3 19]]
[[ 5  5  3  2]
 [ 8 10  3 11]
 [10 14 10 11]
 [13 18 10 19]]
None
[[ 5  5  3  2]
 [ 8 10  3 11]
 [10 14 10 11]
 [13 18 10 19]]


In [99]:
x = np.random.randint(1, 20, 16).reshape(4,4)
print(x)
# 정렬했을 때의 순서 인덱스를 반환
print(np.argsort(x)) # 기본값 axis=1
print(np.argsort(x, axis=0))
print(np.argsort(x, axis=None)) # flatten 된 배열의 인덱스를 반환

[[19  9  9 10]
 [10 18  9 19]
 [ 1 11  9  5]
 [ 6  4 13  7]]
[[1 2 3 0]
 [2 0 1 3]
 [0 3 2 1]
 [1 0 3 2]]
[[2 3 0 2]
 [3 0 1 3]
 [1 2 2 0]
 [0 1 3 1]]
[ 8 13 11 12 15  1  2  6 10  3  4  9 14  5  0  7]


In [104]:
x = np.random.randint(1, 20, 16).reshape(4,4)
print(x)

# 행렬의 내적(inner product) 구할 때 필요
# 3 가지 모두 전치행렬 transpose matrix(aT)로 사용가능
# 3차원 배열도 가능!
print(x.T)
print(np.transpose(x))
print(x.transpose())

[[14 11 19 13]
 [17 14 19 16]
 [17 14 14  5]
 [ 6 12 15 11]]
[[14 17 17  6]
 [11 14 14 12]
 [19 19 14 15]
 [13 16  5 11]]
[[14 17 17  6]
 [11 14 14 12]
 [19 19 14 15]
 [13 16  5 11]]
[[14 17 17  6]
 [11 14 14 12]
 [19 19 14 15]
 [13 16  5 11]]


# 확률과 통계

In [18]:
# mean 평균

print(arr)
print(np.mean(arr))
print(np.mean(arr, axis=0)) 
print(np.mean(arr, axis=1, dtype = np.int16)) 


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
12.0
[10. 11. 12. 13. 14.]
[ 2  7 12 17 22]


In [11]:
# median 중앙값, 중위수

print(arr)
print(np.median(arr))
print(np.median(arr, axis=0)) 
print(np.median(arr, axis=1, dtype = np.int16)) 


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
12.0
[10. 11. 12. 13. 14.]
[ 2.  7. 12. 17. 22.]


In [19]:
# 데이터의 백분위수를 계산
"""
a : 사용할 배열
p : percentile로 백분위수 결과
(axis) : 축 설정
(out) : 변수 반환 유무
(overwrite_input) : 입력 덮어쓰기, 기본값 = False로 
(method) : 백분위수를 추정하는데 사용할 방법을 설정
    1. 'inverted_cdf'
    2. 'averaged_inverted_cdf'
    3. 'closest_observation'
    4. 'interpolated_inverted_cdf'
    5. 'hazen'
    6. 'weibull'
    7. 'linear'
    8. 'median_unbiased'
    9. 'normal_unbiased'
(keepdims) : 차원 유지. True이면 출력 차원을 입력 차원과 동일하게 유지
"""


# 백분위 25%의 intensity
print(np.percentile(arr, 25))

# 백분위 50%의 intensity
print(np.percentile(arr, 50))

# 백분위 75%의 intensity
print(np.percentile(arr, 75))

# 백분위 25, 50 75%의 intensity
print(np.percentile(arr, [25, 50 , 75]))


6.0
12.0
18.0
[ 6. 12. 18.]


In [30]:
# std 표준 편차 : 각 측정값과 평균의 차이를 측정하여 해당 자료의 산포도를 나타내는 값

print(arr)
print(np.std(arr))
print(np.std(arr, axis=0)) 
print(np.std(arr, axis=1, dtype = np.float32)) 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
7.211102550927978
[7.07106781 7.07106781 7.07106781 7.07106781 7.07106781]
[1.4142135 1.4142135 1.4142135 1.4142135 1.4142135]


In [23]:
# var 분산 : 관측값에서 평균을 뺀 값을 제곱하고 모두 더한 후 전체 개수로 나눠서 구한다. 즉, 편차 제곱의 평균

print(arr)
print(np.var(arr))
print(np.var(arr, axis=0)) 
print(np.var(arr, axis=1, dtype = np.float32)) 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
52.0
[50. 50. 50. 50. 50.]
[2. 2. 2. 2. 2.]


In [41]:
arr1 = np.random.randint(1,20, 9).reshape(3, 3)
arr2 = np.random.randint(1, 20, 9).reshape(3, 3)

print(arr)
# 공분산 설명 : https://supermemi.tistory.com/71
print(np.cov(arr)) # 공분산 covariance : 두 변수가 함께 변화를 보이는 지표, 2개의 확률변수의 선형 관계를 나타내는 값
print(np.cov(arr1, arr2, dtype=np.float16)) # arr1의 분산, arr2의 분산과 함께 둘의 공분산 계산
# 피어슨 상관계수 설명 : https://umbum.dev/1006
print(np.corrcoef(arr[:,0], arr[:,1])) #  피어슨 상관계수 값 계산 :  X와 Y 간의 선형 상관 관계를 계량화한 수치
print(np.cumsum(arr, axis=0)) # 누적되는 원소들의 누적 합 계산
print(np.cumprod(arr, axis=1)) # 누적되는 원소들의 누적 곱 계산

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[2.5 2.5 2.5 2.5 2.5]
 [2.5 2.5 2.5 2.5 2.5]
 [2.5 2.5 2.5 2.5 2.5]
 [2.5 2.5 2.5 2.5 2.5]
 [2.5 2.5 2.5 2.5 2.5]]
[[ 26.33   -27.83   -41.84    -2.834   10.5    -22.5   ]
 [-27.83    30.33    42.34     2.834   -9.      29.    ]
 [-41.84    42.34    70.4      4.836  -21.      25.    ]
 [ -2.834    2.834    4.836    0.3333  -1.5      1.5   ]
 [ 10.5     -9.     -21.      -1.5      9.       3.    ]
 [-22.5     29.      25.       1.5      3.      49.    ]]
[[1. 1.]
 [1. 1.]]
[[ 0  1  2  3  4]
 [ 5  7  9 11 13]
 [15 18 21 24 27]
 [30 34 38 42 46]
 [50 55 60 65 70]]
[[      0       0       0       0       0]
 [      5      30     210    1680   15120]
 [     10     110    1320   17160  240240]
 [     15     240    4080   73440 1395360]
 [     20     420    9240  212520 5100480]]


In [42]:
print(np.tril(arr)) # 하삼각행렬 (Lower triangular matrix) 반환
print(np.triu(arr)) # 상삼각행렬 (Upper triangular matrix) 반환

[[ 0  0  0  0  0]
 [ 5  6  0  0  0]
 [10 11 12  0  0]
 [15 16 17 18  0]
 [20 21 22 23 24]]
[[ 0  1  2  3  4]
 [ 0  6  7  8  9]
 [ 0  0 12 13 14]
 [ 0  0  0 18 19]
 [ 0  0  0  0 24]]


 # Set 관련

In [6]:
arr = np.array([1,1,1,2,2,2,3,3,4,5,5,6])
print(np.unique(arr))

set_, cnt = np.unique(arr, return_counts=True)
print(set_)
print(cnt)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[3 3 2 1 2 1]


In [7]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])

print(np.intersect1d(arr1, arr2)) # 교집합
print(np.union1d(arr1, arr2)) # 합집합
print(np.setdiff1d(arr1, arr2)) # 차집합
print(np.setxor1d(arr1, arr2)) # 합집합 - 교집합 (교집합의 여집합)

# 존재 유무 불
print(np.in1d(arr1, arr2)) # 1차원 배열로 반환
print(np.isin(arr1, arr2)) # 넣어준 배열의 차원 그대로 반환


[3 4 5]
[1 2 3 4 5 6 7]
[False False  True  True  True]
[False False  True  True  True]
[1 2]
[1 2 6 7]


# 선형대수

In [20]:
arr = np.random.rand(5,5)

q, r = np.linalg.qr(arr)
print(q); print()
print(r)

[[-0.1318779  -0.712131    0.13825496  0.20223823  0.64456413]
 [-0.4835218  -0.50059903 -0.31810856  0.14120003 -0.62807386]
 [-0.54262538  0.313135   -0.61405375 -0.20891711  0.43219881]
 [-0.67371172  0.25565086  0.6905731   0.05821929 -0.02178233]
 [-0.0220252  -0.28081873  0.16043472 -0.94452443 -0.05282068]]

[[-0.78728945 -0.67715657 -1.26722724 -1.0931003  -0.9140792 ]
 [ 0.         -1.13498578 -0.42547663 -0.14885868 -0.25551329]
 [ 0.          0.         -0.41394965  0.15335667 -0.53774138]
 [ 0.          0.          0.         -0.95397965 -0.40492228]
 [ 0.          0.          0.          0.          0.1448224 ]]


In [19]:
arr1 = np.random.rand(5,5)
arr2 = np.random.rand(5,5)

print(arr1.dot(arr2)); print()
# or
print(np.dot(arr1, arr2)); print()
# or
print(arr1 @ arr2); print()

[[0.36559797 0.64588745 0.68488474 0.53454942 0.48813437]
 [0.99094613 1.3520716  1.57533299 1.32321075 1.34220614]
 [0.95936558 1.39166788 1.80302978 1.48652134 1.83194828]
 [1.03686064 1.29547915 1.45671184 1.2154447  1.08586218]
 [0.88900688 1.47168602 1.79235747 1.39524355 1.66682156]]

[[0.36559797 0.64588745 0.68488474 0.53454942 0.48813437]
 [0.99094613 1.3520716  1.57533299 1.32321075 1.34220614]
 [0.95936558 1.39166788 1.80302978 1.48652134 1.83194828]
 [1.03686064 1.29547915 1.45671184 1.2154447  1.08586218]
 [0.88900688 1.47168602 1.79235747 1.39524355 1.66682156]]

[[0.36559797 0.64588745 0.68488474 0.53454942 0.48813437]
 [0.99094613 1.3520716  1.57533299 1.32321075 1.34220614]
 [0.95936558 1.39166788 1.80302978 1.48652134 1.83194828]
 [1.03686064 1.29547915 1.45671184 1.2154447  1.08586218]
 [0.88900688 1.47168602 1.79235747 1.39524355 1.66682156]]



In [23]:
arr = np.random.rand(5,5)

u, s, v = np.linalg.svd(arr)
print(u); print()
print(s); print()
print(v)

[[-0.36267842  0.31858517 -0.3945214  -0.68066539  0.38472762]
 [-0.63577613  0.46076605  0.01522165  0.21812368 -0.57937355]
 [-0.2524644  -0.7327307  -0.49934775 -0.12601873 -0.3662493 ]
 [-0.45859433 -0.36396127  0.74724371 -0.28858707  0.12477087]
 [-0.43612617 -0.12975382 -0.19078736  0.62446254  0.60547884]]

[2.01686442 1.05730561 0.74881867 0.43389409 0.03155006]

[[-0.58343943 -0.56306759 -0.23269111 -0.45303729 -0.2883841 ]
 [ 0.54955209  0.03257334 -0.40610078 -0.07799845 -0.72521023]
 [-0.47392179  0.17779404  0.2403651   0.61737331 -0.55214331]
 [-0.30968894  0.41753784 -0.81037884  0.1553305   0.22116393]
 [-0.19256645  0.68988789  0.25777461 -0.61918987 -0.1926889 ]]


In [16]:
arr = np.random.rand(5,5)
print(np.linalg.eigvals(arr)); print()

w, v = np.linalg.eig(arr)
print(w)    # eigen values
print()
print(v)   # eigen vectors



[ 2.6597437 +0.j          0.56380311+0.j          0.23978549+0.j
 -0.58862233+0.10644253j -0.58862233-0.10644253j]

[ 2.6597437 +0.j          0.56380311+0.j          0.23978549+0.j
 -0.58862233+0.10644253j -0.58862233-0.10644253j]

[[ 1.73648879e-01+0.j          6.84580410e-01+0.j
  -2.07797630e-01+0.j         -4.50509275e-02+0.06636484j
  -4.50509275e-02-0.06636484j]
 [ 3.96408687e-01+0.j         -1.53418468e-04+0.j
   4.40003988e-01+0.j         -5.51290575e-01+0.27761499j
  -5.51290575e-01-0.27761499j]
 [ 5.74292007e-01+0.j         -5.84033401e-01+0.j
  -7.67456563e-01+0.j          1.52027218e-01-0.00366291j
   1.52027218e-01+0.00366291j]
 [ 4.06203952e-01+0.j         -2.89965647e-01+0.j
   3.94526569e-01+0.j          6.55457071e-01+0.j
   6.55457071e-01-0.j        ]
 [ 5.63820236e-01+0.j         -3.25844364e-01+0.j
   1.36293233e-01+0.j         -1.59583456e-01-0.36654904j
  -1.59583456e-01+0.36654904j]]


In [17]:
arr = np.random.rand(5,5)

print(np.trace(arr)); print()
print(np.linalg.det(arr)); print()


print(np.linalg.inv(arr)); print()
print(np.linalg.pinv(arr)); print()

y = [1,2,3,4,5]
print(np.linalg.solve(arr, y))

1.4533236227673814

-0.198390997111491

[[-1.69482045  0.86608452  2.61720615 -2.07120794 -0.12469817]
 [ 0.58135253 -0.54518232 -0.01739241  1.16467121 -1.00996475]
 [ 0.09217099  1.16764515 -0.73124982  0.31673954 -0.11179493]
 [ 0.51108639  0.00483213  0.26680457 -1.14180828  0.87113038]
 [ 1.1006423  -0.76084456 -2.31337199  2.20351438  1.02170362]]

[[-1.69482045  0.86608452  2.61720615 -2.07120794 -0.12469817]
 [ 0.58135253 -0.54518232 -0.01739241  1.16467121 -1.00996475]
 [ 0.09217099  1.16764515 -0.73124982  0.31673954 -0.11179493]
 [ 0.51108639  0.00483213  0.26680457 -1.14180828  0.87113038]
 [ 1.1006423  -0.76084456 -2.31337199  2.20351438  1.02170362]]

[-1.01935554 -0.95232821  0.94169532  1.10958313  6.56141282]


In [11]:
y = [1,2,3,4,5]
solution, residuals, rank, singular = np.linalg.lstsq(arr, y)
print(solution)
print(residuals)
print(rank)
print(singular)

[ 3.90558838 -2.18967179  3.16384021  1.92401873 -1.07257619]
[]
5
[2.3169312  0.86627475 0.6787801  0.27570244 0.0544881 ]


C:\Users\yookim\AppData\Local\Temp\ipykernel_33848\2394510925.py:2: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  solution, residuals, rank, singular = np.linalg.lstsq(arr, y)
